ufak tefek değişiklikler
skyhancloud/old-bencan.net pull request #1
Opened 2023-12-21 05:41 UTC by exrem

2023-12-21 17:14 UTC, skyhancloud requested changes
Neden min width ekledin onu anlayamadım

2023-12-22 04:05 UTC, exrem commented
<img width="493" alt="Screenshot 2023-12-22 at 08 03 20" src="https://github.com/chimpdev/bencan.net/assets/51994409/0b390832-2c22-4b16-a27c-949905311510">

telefonda github & discord linkleri ayrı ayrı olduğu hâlde repo linkinin min-width'i olmadığı için instagram ile aynı satırı paylaşıyor; pek hoşuma gitmedi benim de, o yüzden :3

2023-12-22 23:24 UTC, chimpdev commented
Bu şekil daha mantıklı geldi bana. Teşekkürler

2023-12-22 23:24 UTC, merged

2023-12-22 23:39 UTC, exrem commented
rica ederim, iyi kodlamalar :3